# Generated by Django 4.0.2 on 2022-05-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product nam')),
                ('category', models.CharField(choices=[('LT', 'Laptop'), ('DT', 'Desktop')], max_length=2)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('memory', models.CharField(choices=[('4', '4GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB')], max_length=3)),
                ('storage', models.CharField(choices=[('256', '256GB'), ('512', '512GB'), ('1000', '1TB'), ('2000', '2TB'), ('4000', '4TB')], max_length=4)),
                ('storage_type', models.CharField(choices=[('1', 'HDD'), ('2', 'SSD')], max_length=1)),
                ('os', models.CharField(max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('tumbnail', models.ImageField(upload_to='products/tumbnails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
