# Generated by Django 4.0.2 on 2022-07-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_category_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(choices=[('dell', 'DELL'), ('hp', 'HP'), ('apple', 'APPLE'), ('asus', 'ASUS'), ('lenovo', 'LENOVO'), ('MSI', 'msi')], default='dell', max_length=55),
        ),
    ]
