# Generated by Django 4.0.2 on 2022-07-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('BDK', 'Badakhshan'), ('BDG', 'Badghis'), ('BGH', 'Baghlan'), ('BLK', 'Balkh'), ('BAM', 'Bamyan'), ('DYK', 'Daykundi'), ('FRH', 'Farah'), ('FRB', 'Faryab'), ('GHZ', 'Ghazni'), ('GHR', 'Ghor'), ('HEL', 'Helmand'), ('HRT', 'Herat'), ('JZJ', 'Jowzjan'), ('KBL', 'Kabul'), ('KDR', 'Kandahar'), ('KPS', 'Kapisa'), ('KST', 'Khost'), ('KNR', 'Kunar'), ('KDZ', 'Kunduz'), ('LGH', 'Laghman'), ('LGR', 'Logar'), ('NGR', 'Nangarhar'), ('NMZ', 'Nimruz'), ('NRT', 'Nuristan'), ('ORZ', 'Oruzgan'), ('PTI', 'Paktia'), ('PTK', 'Paktika'), ('PJR', 'Panjshir'), ('PRW', 'Parwan'), ('SMG', 'Samangan'), ('SRP', 'Sar-e-Pol'), ('TKH', 'Takhar'), ('WDK', 'Wardak'), ('ZBL', 'Zabul')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(choices=[('dell', 'DELL'), ('hp', 'HP'), ('apple', 'APPLE'), ('asus', 'ASUS'), ('lenovo', 'LENOVO'), ('msi', 'MSI')], default='dell', max_length=55),
        ),
    ]
