# Generated by Django 4.0.2 on 2022-05-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resetcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetcodes',
            old_name='code',
            new_name='value',
        ),
    ]
