# Generated by Django 4.0.2 on 2022-07-14 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_address_contact_phone_alter_address_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture_date',
            field=models.DateField(default=datetime.date(2016, 6, 14)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('OD', 'OutForDelivery'), ('D', 'Delivered')], default='P', max_length=2),
        ),
    ]
