# Generated by Django 4.0.4 on 2022-05-30 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('BDK', 'Badakhshan'), ('BDG', 'Badghis'), ('BGH', 'Baghlan'), ('BLK', 'Balkh'), ('BAM', 'Bamyan'), ('DYK', 'Daykundi'), ('FRH', 'Farah'), ('FRB', 'Faryab'), ('GHZ', 'Ghazni'), ('GHR', 'Ghor'), ('HEL', 'Helmand'), ('HRT', 'Herat'), ('JZJ', 'Jowzjan'), ('KBL', 'Kabul'), ('KDR', 'Kandahar'), ('KPS', 'Kapisa'), ('KST', 'Khost'), ('KNR', 'Kunar'), ('KDZ', 'Kunduz'), ('LGH', 'Laghman'), ('LGR', 'Logar'), ('NGR', 'Nangarhar'), ('NMZ', 'Nimruz'), ('NRT', 'Nuristan'), ('ORZ', 'Oruzgan'), ('PTI', 'Paktia'), ('PTK', 'Paktika'), ('PJR', 'Panjshir'), ('PAR', 'Parwan'), ('SMN', 'Samangan'), ('SRP', 'Sar-e-Pol'), ('TKH', 'Takhar'), ('WDK', 'Wardak'), ('ZBL', 'Zabul')], max_length=3)),
                ('district', models.CharField(max_length=55)),
                ('home_address', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
            preserve_default=False,
        ),
    ]
