# Generated by Django 4.0.2 on 2022-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_manufacture_date_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacture_date',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='2016', max_length=4),
        ),
    ]
