# Generated by Django 4.0.2 on 2022-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_code_resetcodes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetcodes',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
