# Generated by Django 4.0.4 on 2022-07-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_vendor'),
        ('core', '0006_remove_product_manufacture_date_product_model'),
    ]

    operations = [
    ]
